export const TASK_LIST_REQ = 'TASK_LIST_REQ'
export const TASK_LIST_RES = 'TASK_LIST_RES'

export const CREATE_TASK_LIST_REQ = 'CREATE_TASK_LIST_REQ'
export const CREATE_TASK_LIST_RES = 'CREATE_TASK_LIST_RES'

export const EDIT_TASK_LIST_REQ = 'EDIT_TASK_LIST_REQ'
export const EDIT_TASK_LIST_RES = 'EDIT_TASK_LIST_RES'

export const REMOVE_TASK_LIST_REQ = 'REMOVE_TASK_LIST_REQ'
export const REMOVE_TASK_LIST_RES = 'REMOVE_TASK_LIST_RES'

export const SELECT_TASK_LIST = 'SELECT_TASK_LIST'