export const FETCH_TASK_BY_LIST_REQ = 'FETCH_TASK_BY_LIST_REQ'
export const FETCH_TASK_BY_LIST_RES = 'FETCH_TASK_BY_LIST_RES'

export const CREATE_TASK_REQ = 'CREATE_TASK_REQ'
export const CREATE_TASK_RES = 'CREATE_TASK_RES'

export const EDIT_TASK_REQ = 'EDIT_TASK_REQ'
export const EDIT_TASK_RES = 'EDIT_TASK_RES'

export const REMOVE_TASK_REQ = 'REMOVE_TASK_REQ'
export const REMOVE_TASK_RES = 'REMOVE_TASK_RES'

export const FETCH_COLLECTION_TASK = 'FETCH_COLLECTION_TASK'
export const SELECT_TASK = 'SELECT_TASK'